# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       git-repo

# >> macros
# << macros

Summary:    Repo helps manage many Git repositories
Version:    1.12.4
Release:    1
Group:      Tools
License:    Apache 2.0
Source0:    git-repo-1.12.4.tar.gz
Source100:  git-repo.yaml
Requires:   python
Requires:   git

%description
git-repo for Mer

The upstream tarball is based off of these upstream Google repos:
  git clone https://android.googlesource.com/tools/repo


%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
install -D -m 755 repo %{buildroot}%{_bindir}/repo
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/repo
# >> files
# << files
